[tool.poetry]
name = "pirataria"
version = "0.1.0"
description = ""
authors = ["Rodrigoneal <rodrigho2006@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
selenium-tools = {git = "https://github.com/digital-path/selenium_tools"}
httpx = "^0.24.1"
free-proxy = "^1.1.1"
parsel = "^1.8.1"
requests-html = "^0.10.0"
playwright = "^1.35.0"
flask = "^2.3.2"
pydantic = "^1.10.9"
deep-translator = "^1.11.1"


[tool.poetry.group.lint.dependencies]
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
